Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> """
Corresponds to Section 3.1 Motivation Case & Figure 2: BPMN Process Model for Intelligent Manufacturing
Implements the core BPMN process definition, activity execution, control flow logic, and boundary event handling
Aligned with UBPMN extension for ubiquitous environment context awareness (Section 3.4)
"""
from enum import Enum
from typing import Dict, List, Tuple, Optional, Set
from dataclasses import dataclass, field

# --------------------------
# Enums for BPMN Element Types
# --------------------------
class ActivityType(Enum):
    """Activity types aligned with Definition 5 in Section 3.3"""
    OPERATIONAL = "operational"
    ADMINISTRATIVE = "administrative"
    DECISION = "decision"

class GatewayType(Enum):
    EXCLUSIVE = "exclusive"  # XOR Gateway
    PARALLEL = "parallel"     # AND Gateway

class BoundaryEventType(Enum):
    """Boundary event types aligned with Definition 12 in Section 5.2"""
    INTERRUPTING = "interrupting"
    NON_INTERRUPTING = "non_interrupting"

# --------------------------
# Core BPMN Element Data Classes
# --------------------------
@dataclass
class Activity:
    """
    BPMN Activity definition, aligned with Definition 5 in Section 3.3
    :param activity_id: Unique identifier of the activity
    :param name: Human-readable name of the activity
    :param activity_type: Type of activity (operational/administrative/decision)
    :param input_data: List of required input data attributes
    :param output_data: List of output data attributes generated by the activity
    :param is_completed: Execution status of the activity
    """
    activity_id: str
    name: str
    activity_type: ActivityType
    input_data: List[str] = field(default_factory=list)
    output_data: List[str] = field(default_factory=list)
    is_completed: bool = False

    def execute(self, input_data: Dict) -> Tuple[bool, Dict]:
        """
        Execute the activity and generate output data
        :param input_data: Dict of input data {attr_name: value}
        :return: (execution_success, output_data_dict)
        """
        # Validate all required input data is provided
        if not set(self.input_data).issubset(input_data.keys()):
            return False, {}
        
        # Administrative activity: inject initial data into the process
        if self.activity_type == ActivityType.ADMINISTRATIVE:
            self.is_completed = True
            return True, input_data
        
        # Operational activity: execute operation without modifying core decision data
        if self.activity_type == ActivityType.OPERATIONAL:
            self.is_completed = True
            return True, {}
        
        # Decision activity: will be handled by DMN model, mark as pending
        self.is_completed = False
        return True, input_data

@dataclass
class Gateway:
    """
    BPMN Gateway definition for control flow routing
    :param gateway_id: Unique identifier of the gateway
    :param name: Human-readable name of the gateway
    :param gateway_type: Type of gateway (exclusive/parallel)
    :param condition_map: Dict {outgoing_sequence_flow_id: condition_expression} for XOR gateways
    """
    gateway_id: str
    name: str
    gateway_type: GatewayType
    condition_map: Dict[str, str] = field(default_factory=dict)

    def evaluate_routing(self, context_data: Dict) -> List[str]:
        """
        Evaluate gateway conditions and return outgoing sequence flow IDs
        :param context_data: Current process context data {attr_name: value}
        :return: List of outgoing sequence flow IDs to follow
        """
        if self.gateway_type == GatewayType.PARALLEL:
            # Parallel gateway: follow all outgoing paths
            return list(self.condition_map.keys())
        
        # Exclusive gateway: follow only the first satisfied condition
        for flow_id, condition in self.condition_map.items():
            try:
                # Evaluate condition with current context data
                if eval(condition, {}, context_data):
                    return [flow_id]
            except:
                continue
        return []

@dataclass
class BoundaryEvent:
    """
    Boundary Event definition for environment change handling, aligned with Definition 12 in Section 5.2
    :param event_id: Unique identifier of the boundary event
    :param attached_to_activity_id: ID of the activity this event is attached to
    :param event_type: Type of boundary event (interrupting/non-interrupting)
    :param trigger_env_var: Environment variable that triggers this event
    :param trigger_condition: Condition to trigger the event (e.g., env_temp_state == "abnormal")
    :param is_triggered: Trigger status of the event
    """
    event_id: str
    attached_to_activity_id: str
    event_type: BoundaryEventType
    trigger_env_var: str
    trigger_condition: str
    is_triggered: bool = False

    def check_trigger(self, context_data: Dict) -> bool:
        """
        Check if the boundary event is triggered by environment context changes
        :param context_data: Current process context data (including environment states)
        :return: True if event is triggered
        """
        try:
            self.is_triggered = eval(self.trigger_condition, {}, context_data)
        except:
            self.is_triggered = False
        return self.is_triggered

# --------------------------
# Core BPMN Process Model (Figure 2)
# --------------------------
class BPMNProcessModel:
    """
    Full BPMN Process Model for Intelligent Manufacturing (Figure 2 in the paper)
    Implements the end-to-end production process with context awareness and boundary event handling
    """
    def __init__(self):
        # Initialize all process elements
        self.activities: Dict[str, Activity] = self._init_activities()
        self.gateways: Dict[str, Gateway] = self._init_gateways()
        self.boundary_events: Dict[str, BoundaryEvent] = self._init_boundary_events()
        
        # Process sequence flow (control flow definition)
        self.sequence_flow: Dict[str, List[str]] = self._init_sequence_flow()
        
        # Process execution state
        self.current_node_id: Optional[str] = "start_event"
        self.completed_activities: Set[str] = set()
        self.process_context: Dict = {}  # Internal + external context data (Definition 7)

    def _init_activities(self) -> Dict[str, Activity]:
        """Initialize all activities in Figure 2, aligned with Definition 5"""
        return {
            "order_received": Activity(
                activity_id="order_received",
                name="Order Received",
                activity_type=ActivityType.ADMINISTRATIVE,
                input_data=[],
                output_data=["order_quantity", "order_type", "delivery_date"]
            ),
            "production_plan": Activity(
                activity_id="production_plan",
                name="Production Plan",
                activity_type=ActivityType.OPERATIONAL,
                input_data=["order_quantity", "delivery_date"],
                output_data=[]
            ),
            "purchase_plan": Activity(
                activity_id="purchase_plan",
                name="Purchase Plan",
                activity_type=ActivityType.OPERATIONAL,
                input_data=["order_quantity", "order_type"],
                output_data=[]
            ),
            "raw_material_procurement": Activity(
                activity_id="raw_material_procurement",
                name="Raw Material Procurement",
                activity_type=ActivityType.OPERATIONAL,
                input_data=["order_quantity"],
                output_data=["raw_material_quantity", "raw_material_specification"]
            ),
            "raw_material_inspection": Activity(
                activity_id="raw_material_inspection",
                name="Raw Material Inspection",
                activity_type=ActivityType.DECISION,
                input_data=["raw_material_quantity", "raw_material_specification"],
                output_data=["inspection_result"]
            ),
            "repurchase": Activity(
                activity_id="repurchase",
                name="Repurchase",
                activity_type=ActivityType.OPERATIONAL,
                input_data=["order_quantity"],
                output_data=["raw_material_quantity", "raw_material_specification"]
            ),
            "manufacturing": Activity(
                activity_id="manufacturing",
                name="Manufacturing",
                activity_type=ActivityType.DECISION,
                input_data=["order_quantity", "delivery_date", "inspection_result", "env_temp_state"],
                output_data=["production_mode"]
            ),
            "production_task_assignment": Activity(
                activity_id="production_task_assignment",
                name="Production Task Assignment",
                activity_type=ActivityType.OPERATIONAL,
                input_data=["production_mode"],
                output_data=[]
            ),
            "reproduction": Activity(
                activity_id="reproduction",
                name="Reproduction",
                activity_type=ActivityType.OPERATIONAL,
                input_data=["order_quantity"],
                output_data=[]
            ),
            "adjust_production_schedule": Activity(
                activity_id="adjust_production_schedule",
                name="Adjust Production Schedule",
                activity_type=ActivityType.OPERATIONAL,
                input_data=["delivery_date", "production_mode"],
                output_data=["delivery_date"]
            ),
            "production_completion": Activity(
                activity_id="production_completion",
                name="Production Completion",
                activity_type=ActivityType.OPERATIONAL,
                input_data=["production_mode", "inspection_result"],
                output_data=[]
            )
        }

    def _init_gateways(self) -> Dict[str, Gateway]:
        """Initialize all gateways in Figure 2"""
        return {
            "parallel_split": Gateway(
                gateway_id="parallel_split",
                name="Parallel Split (Plan Creation)",
                gateway_type=GatewayType.PARALLEL,
                condition_map={"flow_to_production_plan": "", "flow_to_purchase_plan": ""}
            ),
            "parallel_join": Gateway(
                gateway_id="parallel_join",
                name="Parallel Join (Plan Completion)",
                gateway_type=GatewayType.PARALLEL,
                condition_map={"flow_to_procurement": ""}
            ),
            "inspection_gateway": Gateway(
                gateway_id="inspection_gateway",
                name="Inspection Result Gateway",
                gateway_type=GatewayType.EXCLUSIVE,
                condition_map={
                    "flow_to_manufacturing": "inspection_result == 'Accept'",
                    "flow_to_repurchase": "inspection_result == 'Reject'"
                }
            ),
            "quality_gateway": Gateway(
                gateway_id="quality_gateway",
                name="Production Quality Gateway",
                gateway_type=GatewayType.EXCLUSIVE,
                condition_map={
                    "flow_to_completion": "production_mode in ['Single Line', 'Multiple Lines']",
                    "flow_to_reproduction": "production_mode == 'Outsourced'"
                }
            )
        }

    def _init_boundary_events(self) -> Dict[str, BoundaryEvent]:
        """Initialize boundary events for environment change handling (Section 5.2)"""
        return {
            "temp_abnormal_event": BoundaryEvent(
                event_id="temp_abnormal_event",
                attached_to_activity_id="manufacturing",
                event_type=BoundaryEventType.INTERRUPTING,
                trigger_env_var="env_temp_state",
                trigger_condition="env_temp_state == 'abnormal'"
            ),
            "supply_shortage_event": BoundaryEvent(
                event_id="supply_shortage_event",
                attached_to_activity_id="raw_material_procurement",
                event_type=BoundaryEventType.NON_INTERRUPTING,
                trigger_env_var="env_supply_state",
                trigger_condition="env_supply_state == 'shortage'"
            )
        }

    def _init_sequence_flow(self) -> Dict[str, List[str]]:
        """Initialize the control flow sequence of the process (Figure 2)"""
        return {
            "start_event": ["order_received"],
            "order_received": ["parallel_split"],
            "parallel_split": ["production_plan", "purchase_plan"],
            "production_plan": ["parallel_join"],
            "purchase_plan": ["parallel_join"],
            "parallel_join": ["raw_material_procurement"],
            "raw_material_procurement": ["raw_material_inspection"],
            "raw_material_inspection": ["inspection_gateway"],
            "inspection_gateway": ["flow_to_manufacturing", "flow_to_repurchase"],
            "flow_to_repurchase": ["repurchase"],
            "repurchase": ["raw_material_procurement"],
            "flow_to_manufacturing": ["manufacturing"],
            "manufacturing": ["production_task_assignment", "quality_gateway"],
            "quality_gateway": ["flow_to_completion", "flow_to_reproduction"],
            "flow_to_reproduction": ["reproduction", "adjust_production_schedule"],
            "adjust_production_schedule": ["manufacturing"],
            "flow_to_completion": ["production_completion"],
            "production_completion": ["end_event"]
        }

    def update_context(self, new_data: Dict):
        """Update the process context with new internal/external data (Definition 7)"""
        self.process_context.update(new_data)

    def reset_process(self):
        """Reset the process to initial state for new execution"""
        self.current_node_id = "start_event"
        self.completed_activities = set()
        self.process_context = {}
        for activity in self.activities.values():
            activity.is_completed = False
        for event in self.boundary_events.values():
            event.is_triggered = False

    def execute_step(self) -> Tuple[bool, str]:
        """
        Execute one step of the process
        :return: (process_completed, current_node_id)
        """
        if self.current_node_id == "end_event":
            return True, "end_event"
        
        # Handle activity execution
        if self.current_node_id in self.activities:
            current_activity = self.activities[self.current_node_id]
            
            # Check boundary events attached to this activity
            for event in self.boundary_events.values():
                if event.attached_to_activity_id == current_activity.activity_id:
                    if event.check_trigger(self.process_context):
                        # Handle interrupting event: terminate activity and switch flow
                        if event.event_type == BoundaryEventType.INTERRUPTING:
                            current_activity.is_completed = False
                            self.current_node_id = "adjust_production_schedule"
                            return False, self.current_node_id
            
            # Execute activity
            success, output_data = current_activity.execute(self.process_context)
            if success:
                current_activity.is_completed = True
                self.completed_activities.add(current_activity.activity_id)
                self.update_context(output_data)
                # Move to next node
                self.current_node_id = self.sequence_flow[self.current_node_id][0]
            return False, self.current_node_id
        
        # Handle gateway routing
        if self.current_node_id in self.gateways:
            current_gateway = self.gateways[self.current_node_id]
            outgoing_flows = current_gateway.evaluate_routing(self.process_context)
            if len(outgoing_flows) > 0:
                # Follow the first outgoing flow
                next_flow = outgoing_flows[0]
                self.current_node_id = self.sequence_flow[next_flow][0]
            return False, self.current_node_id
        
        # Handle start/end events
        if self.current_node_id == "start_event":
            self.current_node_id = self.sequence_flow["start_event"][0]
            return False, self.current_node_id
        
        return False, self.current_node_id

    def run_full_process(self, initial_context: Dict) -> Tuple[bool, Dict]:
        """
        Run the full process end-to-end with given initial context
        :param initial_context: Initial process context (order data + environment data)
        :return: (process_success, final_context)
        """
        self.reset_process()
        self.update_context(initial_context)
        
        while True:
            completed, current_node = self.execute_step()
            if completed:
                return True, self.process_context
            # Prevent infinite loop
            if current_node in self.completed_activities and len(self.completed_activities) > 20:
                return False, self.process_context
